spring.application.name=api-gateway
server.port=8080

# Eureka
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
spring.cloud.compatibility-verifier.enabled=false

# Routes
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[1].id=provider-service
spring.cloud.gateway.routes[1].uri=lb://PROVIDER-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/providers/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[2].id=schedule-service
spring.cloud.gateway.routes[2].uri=lb://SCHEDULE-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/slots/**
spring.cloud.gateway.routes[2].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[3].id=appointment-service
spring.cloud.gateway.routes[3].uri=lb://APPOINTMENT-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/appointments/**
spring.cloud.gateway.routes[3].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[4].id=payment-service
spring.cloud.gateway.routes[4].uri=lb://PAYMENT-SERVICE
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/payments/**
spring.cloud.gateway.routes[4].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[5].id=medical-record-service
spring.cloud.gateway.routes[5].uri=lb://MEDICAL-RECORD-SERVICE
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/records/**
spring.cloud.gateway.routes[5].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[6].id=review-service
spring.cloud.gateway.routes[6].uri=lb://REVIEW-SERVICE
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/reviews/**
spring.cloud.gateway.routes[6].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[7].id=notification-service
spring.cloud.gateway.routes[7].uri=lb://NOTIFICATION-SERVICE
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/notifications/**
spring.cloud.gateway.routes[7].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[8].id=specialization-route
spring.cloud.gateway.routes[8].uri=lb://PROVIDER-SERVICE
spring.cloud.gateway.routes[8].predicates[0]=Path=/api/specializations/**
spring.cloud.gateway.routes[8].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[9].id=razorpay-route
spring.cloud.gateway.routes[9].uri=lb://PAYMENT-SERVICE
spring.cloud.gateway.routes[9].predicates[0]=Path=/api/payments/razorpay/**
spring.cloud.gateway.routes[9].filters[0]=StripPrefix=1

# API Docs routes for Swagger
spring.cloud.gateway.routes[10].id=auth-api-docs
spring.cloud.gateway.routes[10].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[10].predicates[0]=Path=/api-docs/auth
spring.cloud.gateway.routes[10].filters[0]=RewritePath=/api-docs/auth,/v3/api-docs

spring.cloud.gateway.routes[11].id=provider-api-docs
spring.cloud.gateway.routes[11].uri=lb://PROVIDER-SERVICE
spring.cloud.gateway.routes[11].predicates[0]=Path=/api-docs/provider
spring.cloud.gateway.routes[11].filters[0]=RewritePath=/api-docs/provider,/v3/api-docs

spring.cloud.gateway.routes[12].id=schedule-api-docs
spring.cloud.gateway.routes[12].uri=lb://SCHEDULE-SERVICE
spring.cloud.gateway.routes[12].predicates[0]=Path=/api-docs/schedule
spring.cloud.gateway.routes[12].filters[0]=RewritePath=/api-docs/schedule,/v3/api-docs

spring.cloud.gateway.routes[13].id=appointment-api-docs
spring.cloud.gateway.routes[13].uri=lb://APPOINTMENT-SERVICE
spring.cloud.gateway.routes[13].predicates[0]=Path=/api-docs/appointment
spring.cloud.gateway.routes[13].filters[0]=RewritePath=/api-docs/appointment,/v3/api-docs

spring.cloud.gateway.routes[14].id=payment-api-docs
spring.cloud.gateway.routes[14].uri=lb://PAYMENT-SERVICE
spring.cloud.gateway.routes[14].predicates[0]=Path=/api-docs/payment
spring.cloud.gateway.routes[14].filters[0]=RewritePath=/api-docs/payment,/v3/api-docs

spring.cloud.gateway.routes[15].id=medical-record-api-docs
spring.cloud.gateway.routes[15].uri=lb://MEDICAL-RECORD-SERVICE
spring.cloud.gateway.routes[15].predicates[0]=Path=/api-docs/medical-record
spring.cloud.gateway.routes[15].filters[0]=RewritePath=/api-docs/medical-record,/v3/api-docs

spring.cloud.gateway.routes[16].id=review-api-docs
spring.cloud.gateway.routes[16].uri=lb://REVIEW-SERVICE
spring.cloud.gateway.routes[16].predicates[0]=Path=/api-docs/review
spring.cloud.gateway.routes[16].filters[0]=RewritePath=/api-docs/review,/v3/api-docs

spring.cloud.gateway.routes[17].id=notification-api-docs
spring.cloud.gateway.routes[17].uri=lb://NOTIFICATION-SERVICE
spring.cloud.gateway.routes[17].predicates[0]=Path=/api-docs/notification
spring.cloud.gateway.routes[17].filters[0]=RewritePath=/api-docs/notification,/v3/api-docs

# Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.urls-primary-name=Auth Service
springdoc.swagger-ui.urls[0].name=Auth Service
springdoc.swagger-ui.urls[0].url=/api-docs/auth
springdoc.swagger-ui.urls[1].name=Provider Service
springdoc.swagger-ui.urls[1].url=/api-docs/provider
springdoc.swagger-ui.urls[2].name=Schedule Service
springdoc.swagger-ui.urls[2].url=/api-docs/schedule
springdoc.swagger-ui.urls[3].name=Appointment Service
springdoc.swagger-ui.urls[3].url=/api-docs/appointment
springdoc.swagger-ui.urls[4].name=Payment Service
springdoc.swagger-ui.urls[4].url=/api-docs/payment
springdoc.swagger-ui.urls[5].name=Medical Record Service
springdoc.swagger-ui.urls[5].url=/api-docs/medical-record
springdoc.swagger-ui.urls[6].name=Review Service
springdoc.swagger-ui.urls[6].url=/api-docs/review
springdoc.swagger-ui.urls[7].name=Notification Service
springdoc.swagger-ui.urls[7].url=/api-docs/notification